// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Jizw7M0z5KXnqIzgeD2_0dLAYZbdMEo',
    appId: '1:484691912188:web:b92b832700be7e20fd3e79',
    messagingSenderId: '484691912188',
    projectId: 'greg-sausage',
    authDomain: 'greg-sausage.firebaseapp.com',
    storageBucket: 'greg-sausage.appspot.com',
    measurementId: 'G-EMF2XQ0BZX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhW40AoP6aH0cGVIpacmCREua3eOGmSu4',
    appId: '1:484691912188:android:10788d4ed99c5215fd3e79',
    messagingSenderId: '484691912188',
    projectId: 'greg-sausage',
    storageBucket: 'greg-sausage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAj0zl6cRIlaBLrmNHb9vUUtsc7P2AYwo',
    appId: '1:484691912188:ios:16d58983184a29f9fd3e79',
    messagingSenderId: '484691912188',
    projectId: 'greg-sausage',
    storageBucket: 'greg-sausage.appspot.com',
    iosBundleId: 'com.example.gregSausageRoll',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAj0zl6cRIlaBLrmNHb9vUUtsc7P2AYwo',
    appId: '1:484691912188:ios:16d58983184a29f9fd3e79',
    messagingSenderId: '484691912188',
    projectId: 'greg-sausage',
    storageBucket: 'greg-sausage.appspot.com',
    iosBundleId: 'com.example.gregSausageRoll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9Jizw7M0z5KXnqIzgeD2_0dLAYZbdMEo',
    appId: '1:484691912188:web:8ffeb51980fa9c2cfd3e79',
    messagingSenderId: '484691912188',
    projectId: 'greg-sausage',
    authDomain: 'greg-sausage.firebaseapp.com',
    storageBucket: 'greg-sausage.appspot.com',
    measurementId: 'G-DHVJSJX40T',
  );
}
